import { Job, SkillTrend } from "@/types";

// ============================================================
// MOCK JOB DATASET — 30 rich postings
// ============================================================
export const JOBS: Job[] = [
  {
    id: "job-001",
    title: "Senior Data Scientist",
    company: "Stripe",
    location: "San Francisco, CA",
    type: "hybrid",
    seniority: "senior",
    salaryMin: 160000,
    salaryMax: 210000,
    skills: ["Python", "Machine Learning", "PyTorch", "SQL", "Statistics", "MLflow", "Spark"],
    description: "Lead ML initiatives powering Stripe's fraud detection and risk models. You will own the full ML lifecycle from research to production.",
    requirements: ["5+ years ML experience", "Strong Python + PyTorch skills", "Experience with large-scale distributed systems", "PhD or Master's in CS/Statistics preferred"],
    responsibilities: ["Build and deploy fraud detection models", "A/B test ML model variants", "Mentor junior data scientists", "Partner with product teams"],
    postedAt: "2026-07-28T00:00:00Z",
    status: "active",
    industry: "FinTech",
    companySize: "5000+",
    matchScore: 87,
  },
  {
    id: "job-002",
    title: "Machine Learning Engineer",
    company: "OpenAI",
    location: "Remote",
    type: "remote",
    seniority: "mid",
    salaryMin: 140000,
    salaryMax: 185000,
    skills: ["Python", "PyTorch", "LLMs", "CUDA", "Distributed Training", "RAG", "Vector Databases"],
    description: "Work on cutting-edge LLM infrastructure powering GPT models. Build training pipelines and inference optimization.",
    requirements: ["3+ years ML engineering", "Strong Python + CUDA", "Experience with transformer models", "Distributed systems experience"],
    responsibilities: ["Build distributed training pipelines", "Optimize model inference", "Integrate retrieval systems", "Write technical documentation"],
    postedAt: "2026-08-01T00:00:00Z",
    status: "active",
    industry: "AI/ML",
    companySize: "1000-5000",
    matchScore: 92,
  },
  {
    id: "job-003",
    title: "Data Analyst",
    company: "Spotify",
    location: "New York, NY",
    type: "hybrid",
    seniority: "mid",
    salaryMin: 95000,
    salaryMax: 130000,
    skills: ["SQL", "Python", "Tableau", "Statistics", "A/B Testing", "Looker", "dbt"],
    description: "Drive data-informed decisions for Spotify's growth team. Own analytics for user acquisition and engagement metrics.",
    requirements: ["2+ years analytics experience", "Strong SQL skills", "Experience with BI tools", "Solid statistics fundamentals"],
    responsibilities: ["Build analytics dashboards", "Run A/B tests", "Produce weekly insight reports", "Collaborate with product managers"],
    postedAt: "2026-07-25T00:00:00Z",
    status: "active",
    industry: "Media/Entertainment",
    companySize: "5000+",
    matchScore: 78,
  },
  {
    id: "job-004",
    title: "NLP Engineer",
    company: "Anthropic",
    location: "San Francisco, CA",
    type: "onsite",
    seniority: "senior",
    salaryMin: 170000,
    salaryMax: 230000,
    skills: ["Python", "NLP", "Transformers", "PyTorch", "RLHF", "Prompt Engineering", "LLMs"],
    description: "Build the NLP infrastructure behind Claude. Work on alignment, evaluation, and novel training techniques.",
    requirements: ["PhD in NLP/ML preferred", "4+ years NLP experience", "Publications at top venues a plus", "Strong Python + research skills"],
    responsibilities: ["Research and implement NLP techniques", "Build evaluation frameworks", "Contribute to safety research", "Collaborate with alignment team"],
    postedAt: "2026-08-03T00:00:00Z",
    status: "active",
    industry: "AI/ML",
    companySize: "500-1000",
    matchScore: 74,
  },
  {
    id: "job-005",
    title: "Data Engineer",
    company: "Airbnb",
    location: "Remote",
    type: "remote",
    seniority: "mid",
    salaryMin: 120000,
    salaryMax: 160000,
    skills: ["Python", "Spark", "Airflow", "SQL", "dbt", "Kafka", "AWS", "Redshift"],
    description: "Build the data infrastructure that powers Airbnb's analytics and ML platforms. Own ETL pipelines for petabytes of data.",
    requirements: ["3+ years data engineering", "Strong Spark + Python", "Experience with cloud data warehouses", "Knowledge of streaming systems"],
    responsibilities: ["Build and maintain ETL pipelines", "Optimize query performance", "Design data models", "Support ML team with feature engineering"],
    postedAt: "2026-07-30T00:00:00Z",
    status: "active",
    industry: "Travel/Tech",
    companySize: "5000+",
    matchScore: 65,
  },
  {
    id: "job-006",
    title: "AI Product Manager",
    company: "Google",
    location: "Mountain View, CA",
    type: "hybrid",
    seniority: "senior",
    salaryMin: 175000,
    salaryMax: 220000,
    skills: ["Product Management", "AI/ML", "Python", "SQL", "Stakeholder Management", "PRD Writing"],
    description: "Lead AI product strategy for Google's Search AI features. Define roadmap, work with research and engineering.",
    requirements: ["5+ years PM experience", "Technical background in CS or ML", "Experience shipping AI products", "Strong communication skills"],
    responsibilities: ["Define product vision for AI features", "Work with researchers and engineers", "Drive go-to-market strategy", "Analyze user metrics"],
    postedAt: "2026-07-22T00:00:00Z",
    status: "active",
    industry: "Technology",
    companySize: "5000+",
    matchScore: 56,
  },
  {
    id: "job-007",
    title: "MLOps Engineer",
    company: "Uber",
    location: "San Francisco, CA",
    type: "hybrid",
    seniority: "mid",
    salaryMin: 135000,
    salaryMax: 175000,
    skills: ["Python", "Kubernetes", "MLflow", "Docker", "Airflow", "CI/CD", "AWS", "TensorFlow"],
    description: "Build and maintain the ML platform that powers Uber's pricing, ETA, and matching models.",
    requirements: ["3+ years MLOps/DevOps", "Strong containerization skills", "Experience with model serving", "Knowledge of CI/CD pipelines"],
    responsibilities: ["Build model deployment pipelines", "Monitor model performance", "Design feature stores", "Maintain infrastructure as code"],
    postedAt: "2026-08-02T00:00:00Z",
    status: "active",
    industry: "Transportation/Tech",
    companySize: "5000+",
    matchScore: 71,
  },
  {
    id: "job-008",
    title: "Research Scientist – Computer Vision",
    company: "Meta AI",
    location: "Menlo Park, CA",
    type: "onsite",
    seniority: "senior",
    salaryMin: 180000,
    salaryMax: 250000,
    skills: ["Python", "PyTorch", "Computer Vision", "CNNs", "Transformers", "CUDA", "Research"],
    description: "Conduct fundamental and applied research in computer vision for AR/VR applications at Meta.",
    requirements: ["PhD in CS/ML/CV", "Strong publication record", "Expert PyTorch + CUDA", "5+ years research experience"],
    responsibilities: ["Publish research at top venues", "Build novel CV architectures", "Collaborate with product teams", "Mentor interns"],
    postedAt: "2026-07-20T00:00:00Z",
    status: "active",
    industry: "Social Media/Tech",
    companySize: "5000+",
    matchScore: 63,
  },
  {
    id: "job-009",
    title: "Junior Data Analyst",
    company: "Notion",
    location: "New York, NY",
    type: "remote",
    seniority: "entry",
    salaryMin: 70000,
    salaryMax: 90000,
    skills: ["SQL", "Excel", "Python", "Tableau", "A/B Testing"],
    description: "Join Notion's growth analytics team as a junior analyst. Great role for recent grads with strong SQL skills.",
    requirements: ["1+ year analytics experience or strong internship", "Strong SQL", "Basic Python", "Excellent communication"],
    responsibilities: ["Build weekly reports", "Support A/B experiments", "Create dashboards", "Answer ad-hoc data questions"],
    postedAt: "2026-08-04T00:00:00Z",
    status: "active",
    industry: "SaaS/Productivity",
    companySize: "500-1000",
    matchScore: 85,
  },
  {
    id: "job-010",
    title: "Lead ML Engineer",
    company: "Netflix",
    location: "Los Gatos, CA",
    type: "hybrid",
    seniority: "lead",
    salaryMin: 200000,
    salaryMax: 280000,
    skills: ["Python", "Scala", "Spark", "PyTorch", "Recommendation Systems", "A/B Testing", "Distributed Systems"],
    description: "Lead the ML engineering team building Netflix's recommendation systems serving 260M+ subscribers.",
    requirements: ["7+ years ML engineering", "Experience leading teams", "Strong distributed systems", "Recommendation systems experience preferred"],
    responsibilities: ["Lead ML engineering team of 8", "Define ML architecture", "Drive A/B test strategy", "Recruit and mentor engineers"],
    postedAt: "2026-07-18T00:00:00Z",
    status: "active",
    industry: "Media/Tech",
    companySize: "5000+",
    matchScore: 59,
  },
  {
    id: "job-011",
    title: "Data Scientist – Growth",
    company: "Figma",
    location: "San Francisco, CA",
    type: "hybrid",
    seniority: "mid",
    salaryMin: 130000,
    salaryMax: 165000,
    skills: ["Python", "SQL", "Statistics", "Causal Inference", "A/B Testing", "R", "Looker"],
    description: "Use data science to drive Figma's growth. Own experimentation frameworks and user acquisition analytics.",
    requirements: ["3+ years data science", "Strong statistics and experimentation", "Good Python/R", "Experience with growth metrics"],
    responsibilities: ["Design growth experiments", "Build causal inference models", "Create user segmentation models", "Partner with growth PMs"],
    postedAt: "2026-07-29T00:00:00Z",
    status: "active",
    industry: "Design/Tech",
    companySize: "1000-5000",
    matchScore: 80,
  },
  {
    id: "job-012",
    title: "Quantitative Analyst",
    company: "Two Sigma",
    location: "New York, NY",
    type: "onsite",
    seniority: "mid",
    salaryMin: 155000,
    salaryMax: 200000,
    skills: ["Python", "Statistics", "Time Series", "Machine Learning", "C++", "Finance"],
    description: "Develop quantitative trading strategies using ML and statistical methods for Two Sigma's systematic funds.",
    requirements: ["Strong math/statistics background", "Python + C++", "Financial markets knowledge", "PhD preferred"],
    responsibilities: ["Research alpha signals", "Build backtesting frameworks", "Develop trading strategies", "Analyze market microstructure"],
    postedAt: "2026-07-26T00:00:00Z",
    status: "active",
    industry: "Finance/Quant",
    companySize: "1000-5000",
    matchScore: 52,
  },
  {
    id: "job-013",
    title: "AI/ML Engineer",
    company: "Salesforce",
    location: "San Francisco, CA",
    type: "hybrid",
    seniority: "mid",
    salaryMin: 140000,
    salaryMax: 180000,
    skills: ["Python", "PyTorch", "LLMs", "RAG", "Vector Databases", "REST APIs", "AWS"],
    description: "Build Einstein AI features that help millions of Salesforce customers leverage AI for CRM.",
    requirements: ["3+ years ML engineering", "Experience with LLMs and RAG", "Strong Python skills", "REST API experience"],
    responsibilities: ["Build LLM-powered CRM features", "Integrate vector search", "Build AI APIs", "Optimize model performance"],
    postedAt: "2026-08-01T00:00:00Z",
    status: "active",
    industry: "CRM/SaaS",
    companySize: "5000+",
    matchScore: 77,
  },
  {
    id: "job-014",
    title: "Software Engineer – ML Platform",
    company: "Databricks",
    location: "Remote",
    type: "remote",
    seniority: "mid",
    salaryMin: 145000,
    salaryMax: 190000,
    skills: ["Python", "Scala", "Spark", "MLflow", "Kubernetes", "Java", "Distributed Systems"],
    description: "Build the tools that thousands of data scientists use daily — the Databricks ML platform.",
    requirements: ["3+ years software engineering", "Strong distributed systems", "Python + Scala/Java", "ML platform experience a plus"],
    responsibilities: ["Build ML experiment tracking", "Develop model serving infrastructure", "Contribute to open-source MLflow", "Design APIs for data scientists"],
    postedAt: "2026-07-31T00:00:00Z",
    status: "active",
    industry: "Data/Tech",
    companySize: "5000+",
    matchScore: 68,
  },
  {
    id: "job-015",
    title: "Data Science Intern",
    company: "LinkedIn",
    location: "Sunnyvale, CA",
    type: "onsite",
    seniority: "entry",
    salaryMin: 55000,
    salaryMax: 75000,
    skills: ["Python", "SQL", "Statistics", "Machine Learning", "Data Visualization"],
    description: "12-week summer internship on LinkedIn's data science team. Work on real products with full-time mentorship.",
    requirements: ["Pursuing BS/MS in CS/Statistics/Math", "Strong Python + SQL", "Machine learning coursework", "Strong communication"],
    responsibilities: ["Complete a defined data science project", "Present findings to senior leadership", "Collaborate with full-time team", "Learn from structured mentorship"],
    postedAt: "2026-08-05T00:00:00Z",
    status: "active",
    industry: "Social/Professional",
    companySize: "5000+",
    matchScore: 90,
  },
];

// ============================================================
// COMPANIES
// ============================================================
export const COMPANIES = [
  "Stripe", "OpenAI", "Anthropic", "Google", "Meta", "Microsoft",
  "Amazon", "Netflix", "Airbnb", "Uber", "Spotify", "Figma",
  "Databricks", "Salesforce", "Two Sigma", "LinkedIn", "Notion",
];

// ============================================================
// SKILLS TAXONOMY
// ============================================================
export const SKILLS_TAXONOMY: Record<string, string[]> = {
  "Programming Languages": ["Python", "R", "Scala", "Java", "C++", "JavaScript", "TypeScript", "Go", "Rust"],
  "Machine Learning": ["Machine Learning", "Deep Learning", "PyTorch", "TensorFlow", "Keras", "scikit-learn", "XGBoost", "LightGBM"],
  "LLMs & AI": ["LLMs", "RAG", "Prompt Engineering", "LangChain", "Vector Databases", "RLHF", "Fine-tuning", "Embeddings"],
  "Data Engineering": ["SQL", "Spark", "Airflow", "dbt", "Kafka", "Flink", "ETL", "Redshift", "BigQuery", "Snowflake"],
  "MLOps": ["MLflow", "Kubeflow", "Docker", "Kubernetes", "CI/CD", "Model Serving", "Feature Stores"],
  "Analytics": ["Tableau", "Looker", "Power BI", "Excel", "A/B Testing", "Statistics", "Causal Inference"],
  "Cloud": ["AWS", "GCP", "Azure", "S3", "EC2", "Lambda", "Cloud Run"],
  "NLP": ["NLP", "Transformers", "BERT", "GPT", "Named Entity Recognition", "Text Classification"],
  "Computer Vision": ["Computer Vision", "CNNs", "Object Detection", "OpenCV", "YOLO"],
};

export const ALL_SKILLS = Object.values(SKILLS_TAXONOMY).flat();

// ============================================================
// SKILL TRENDS DATA
// ============================================================
const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function makeTrend(base: number, growth: number) {
  return months.map((month, i) => ({
    month,
    count: Math.round(base + growth * i + (Math.random() - 0.5) * base * 0.1),
  }));
}

export const SKILL_TRENDS: SkillTrend[] = [
  { skill: "Python", category: "Programming Languages", trend: makeTrend(8500, 200), totalMentions: 112400, growthRate: 12.3, avgSalaryImpact: 8200 },
  { skill: "LLMs", category: "LLMs & AI", trend: makeTrend(2000, 800), totalMentions: 34200, growthRate: 187.4, avgSalaryImpact: 24000 },
  { skill: "RAG", category: "LLMs & AI", trend: makeTrend(500, 600), totalMentions: 12800, growthRate: 312.5, avgSalaryImpact: 22000 },
  { skill: "PyTorch", category: "Machine Learning", trend: makeTrend(4200, 320), totalMentions: 58300, growthRate: 43.8, avgSalaryImpact: 18000 },
  { skill: "SQL", category: "Data Engineering", trend: makeTrend(9200, 80), totalMentions: 118000, growthRate: 5.2, avgSalaryImpact: 6000 },
  { skill: "Spark", category: "Data Engineering", trend: makeTrend(3400, 100), totalMentions: 42000, growthRate: 8.9, avgSalaryImpact: 12000 },
  { skill: "MLflow", category: "MLOps", trend: makeTrend(1200, 280), totalMentions: 18400, growthRate: 95.2, avgSalaryImpact: 15000 },
  { skill: "Kubernetes", category: "MLOps", trend: makeTrend(2800, 160), totalMentions: 34800, growthRate: 34.5, avgSalaryImpact: 14000 },
  { skill: "Vector Databases", category: "LLMs & AI", trend: makeTrend(300, 500), totalMentions: 8200, growthRate: 428.6, avgSalaryImpact: 20000 },
  { skill: "dbt", category: "Data Engineering", trend: makeTrend(900, 220), totalMentions: 14200, growthRate: 112.3, avgSalaryImpact: 10000 },
  { skill: "Airflow", category: "Data Engineering", trend: makeTrend(2100, 140), totalMentions: 28400, growthRate: 28.7, avgSalaryImpact: 11000 },
  { skill: "Tableau", category: "Analytics", trend: makeTrend(3800, -40), totalMentions: 42000, growthRate: -3.1, avgSalaryImpact: 4000 },
  { skill: "R", category: "Programming Languages", trend: makeTrend(2200, -60), totalMentions: 24000, growthRate: -8.2, avgSalaryImpact: 3000 },
  { skill: "AWS", category: "Cloud", trend: makeTrend(5200, 180), totalMentions: 68000, growthRate: 18.4, avgSalaryImpact: 13000 },
  { skill: "A/B Testing", category: "Analytics", trend: makeTrend(2900, 80), totalMentions: 36000, growthRate: 9.7, avgSalaryImpact: 8000 },
];

// ============================================================
// SALARY BENCHMARKS BY ROLE
// ============================================================
export const SALARY_DATA: Record<string, { entry: [number,number], mid: [number,number], senior: [number,number], lead: [number,number] }> = {
  "Data Scientist": { entry: [85000, 110000], mid: [120000, 155000], senior: [155000, 210000], lead: [200000, 280000] },
  "Machine Learning Engineer": { entry: [95000, 125000], mid: [130000, 170000], senior: [165000, 220000], lead: [210000, 290000] },
  "Data Analyst": { entry: [60000, 85000], mid: [88000, 120000], senior: [115000, 155000], lead: [145000, 195000] },
  "Data Engineer": { entry: [80000, 110000], mid: [115000, 150000], senior: [148000, 200000], lead: [195000, 265000] },
  "NLP Engineer": { entry: [90000, 120000], mid: [125000, 165000], senior: [165000, 225000], lead: [210000, 285000] },
  "MLOps Engineer": { entry: [85000, 115000], mid: [120000, 158000], senior: [155000, 210000], lead: [200000, 270000] },
  "AI Research Scientist": { entry: [100000, 135000], mid: [140000, 185000], senior: [180000, 250000], lead: [240000, 320000] },
  "Software Engineer": { entry: [75000, 105000], mid: [110000, 150000], senior: [150000, 205000], lead: [195000, 270000] },
};

// ============================================================
// CAREER PATHS (taxonomy graph)
// ============================================================
export const CAREER_PATHS: Record<string, string[]> = {
  "Data Analyst": ["Data Scientist", "Analytics Engineer", "Business Intelligence Engineer", "Product Analyst"],
  "Data Scientist": ["Senior Data Scientist", "Machine Learning Engineer", "AI Research Scientist", "Data Science Manager"],
  "Machine Learning Engineer": ["Senior ML Engineer", "MLOps Engineer", "AI Research Scientist", "Lead ML Engineer"],
  "Software Engineer": ["Data Engineer", "Machine Learning Engineer", "MLOps Engineer", "Backend Engineer"],
  "Data Engineer": ["Senior Data Engineer", "Analytics Engineer", "Data Architect", "Platform Engineer"],
  "Business Analyst": ["Data Analyst", "Product Manager", "Analytics Engineer"],
};

// ============================================================
// LEARNING RESOURCES BY SKILL
// ============================================================
export const LEARNING_RESOURCES: Record<string, { title: string; url: string; platform: string; type: string }[]> = {
  Python: [
    { title: "Python for Everybody", url: "https://coursera.org", platform: "Coursera", type: "course" },
    { title: "Build 5 Python Projects", url: "https://replit.com", platform: "Replit", type: "project" },
  ],
  "Machine Learning": [
    { title: "Machine Learning Specialization", url: "https://coursera.org", platform: "Coursera", type: "course" },
    { title: "Hands-On Machine Learning", url: "https://oreilly.com", platform: "O'Reilly", type: "article" },
  ],
  PyTorch: [
    { title: "Deep Learning with PyTorch", url: "https://udemy.com", platform: "Udemy", type: "course" },
    { title: "Build a Neural Network from Scratch", url: "https://github.com", platform: "GitHub", type: "project" },
  ],
  LLMs: [
    { title: "LLM Bootcamp", url: "https://fullstackdeeplearning.com", platform: "FSDL", type: "course" },
    { title: "LLM Engineer Certification", url: "https://deeplearning.ai", platform: "DeepLearning.AI", type: "certification" },
  ],
  RAG: [
    { title: "Building RAG Applications", url: "https://deeplearning.ai", platform: "DeepLearning.AI", type: "course" },
    { title: "RAG with LangChain Project", url: "https://github.com", platform: "GitHub", type: "project" },
  ],
  SQL: [
    { title: "SQL for Data Science", url: "https://coursera.org", platform: "Coursera", type: "course" },
    { title: "Mode Analytics SQL Tutorial", url: "https://mode.com", platform: "Mode", type: "article" },
  ],
  "Vector Databases": [
    { title: "Vector Databases: from Embeddings to Applications", url: "https://deeplearning.ai", platform: "DeepLearning.AI", type: "course" },
  ],
  MLflow: [
    { title: "MLflow Tracking Tutorial", url: "https://mlflow.org", platform: "MLflow Docs", type: "article" },
    { title: "ML Experiment Tracking Project", url: "https://github.com", platform: "GitHub", type: "project" },
  ],
  Kubernetes: [
    { title: "Kubernetes for Beginners", url: "https://udemy.com", platform: "Udemy", type: "course" },
    { title: "CKA Certification", url: "https://cncf.io", platform: "CNCF", type: "certification" },
  ],
  AWS: [
    { title: "AWS Solutions Architect", url: "https://aws.amazon.com", platform: "AWS", type: "certification" },
    { title: "Cloud Practitioner Essentials", url: "https://aws.amazon.com", platform: "AWS", type: "course" },
  ],
};

// ============================================================
// ADMIN STATS
// ============================================================
export const ADMIN_STATS = {
  totalUsers: 8420,
  activeUsers: 3210,
  totalJobs: 48200,
  totalReports: 24600,
  reportsToday: 142,
  newUsersToday: 38,
  modelLatency: 1.24,
  apiUptime: 99.8,
  pendingModeration: 12,
};

export const SYSTEM_HEALTH = [
  { name: "Auth Service", status: "healthy", latency: 42, uptime: 99.99 },
  { name: "Core API", status: "healthy", latency: 128, uptime: 99.95 },
  { name: "NLP Pipeline", status: "healthy", latency: 890, uptime: 99.72 },
  { name: "ML Inference", status: "healthy", latency: 1240, uptime: 99.68 },
  { name: "LLM Orchestration", status: "degraded", latency: 3200, uptime: 98.40 },
  { name: "Vector Store", status: "healthy", latency: 65, uptime: 99.91 },
  { name: "Database", status: "healthy", latency: 18, uptime: 99.99 },
];
